apiVersion: v1
kind: Service
metadata:
  name: security-monitor-backend
  namespace: security-monitor
  labels:
    app: security-monitor-backend
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: security-monitor-backend
