apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-monitor-backend
  namespace: security-monitor
  labels:
    app: security-monitor-backend
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: security-monitor-backend
  template:
    metadata:
      labels:
        app: security-monitor-backend
        component: backend
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: backend
        image: 299138067566.dkr.ecr.eu-central-1.amazonaws.com/devops-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: security-monitor-secrets
              key: secret-key
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: security-monitor-secrets
              key: mysql-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: security-monitor-secrets
              key: mysql-password
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: security-monitor-config
              key: LOG_LEVEL
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: security-monitor-config
              key: MYSQL_DATABASE
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: security-monitor-config
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: security-monitor-config
              key: MYSQL_PORT
        - name: ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: security-monitor-config
              key: ALGORITHM
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            configMapKeyRef:
              name: security-monitor-config
              key: ACCESS_TOKEN_EXPIRE_MINUTES
        - name: BACKEND_CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: security-monitor-config
              key: BACKEND_CORS_ORIGINS
        - name: DATABASE_URL
          value: "mysql+pymysql://$(MYSQL_USER):$(MYSQL_PASSWORD)@$(MYSQL_HOST):$(MYSQL_PORT)/$(MYSQL_DATABASE)"
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
